site_name: Asset Allocation System
site_author: Aditya Giri Goswami (Python Development Intern)
site_description: Complete functional and use case documentation in a single file.

theme:
  name: material
  Optional: Customize Material for MkDocs further
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  language: en
  
# Navigation structure
nav:
  - Home: index.md
  - Project Overview: project-overview.md
  - Functional Documentation: functional-docs.md
  - Use Cases: use-cases.md
  - Database Schema: db_schema.md



# Extensions for clean formatting (like better lists and notes)
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true